let db;
let universeMeta={};
let privateMeta=null;
const LOCAL_KEY='psxPrivateSnapshotV1';
const $=id=>document.getElementById(id);
const f=n=>n==null||n===''?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
const pct=n=>n==null||n===''?'—':`${Number(n)>=0?'+':''}${f(n)}%`;
const score=n=>n==null?'—':f(n);
const histLow=s=>s.lowestValue??null;
const histHigh=s=>s.highestValue??null;
const histPos=s=>{const lo=histLow(s),hi=histHigh(s);return lo==null||hi==null||hi<=lo||s.price==null?null:Math.max(0,Math.min(100,(s.price-lo)/(hi-lo)*100));};
function clone(x){return JSON.parse(JSON.stringify(x));}
function sanitizePublicMarket(market){const out=clone(market);out.meta=out.meta||{};if(out.meta.indexDataFresh===false){out.market={...(out.market||{}),kse100:null,kse100Change:null,allShare:null,allShareChange:null,ogti:null,ogtiChange:null};}if(out.meta.stockDataFresh===false){out.stocks=(out.stocks||[]).map(s=>({symbol:s.symbol,company:s.company,sector:s.sector,lowestValue:s.lowestValue??null,highestValue:s.highestValue??null,historicalSource:s.historicalSource??null,state:'STALE SNAPSHOT',risk:'DO NOT USE'}));}return out;}
function mergeUniverse(master,market){const marketStocks=Array.isArray(market.stocks)?market.stocks:[];const masterStocks=Array.isArray(master?.stocks)?master.stocks:[];const byMarket=new Map(marketStocks.map(s=>[String(s.symbol||'').toUpperCase(),s]));const merged=[];const seen=new Set();for(const base of masterStocks){const symbol=String(base.symbol||'').trim().toUpperCase();if(!symbol)continue;const live=byMarket.get(symbol)||{};merged.push({state:'UNSCORED',risk:'DATA ONLY',...base,...live,symbol,company:base.company||live.company||symbol,sector:base.sector||live.sector||'Unclassified'});seen.add(symbol);}for(const live of marketStocks){const symbol=String(live.symbol||'').trim().toUpperCase();if(!symbol||seen.has(symbol))continue;merged.push({state:'UNSCORED',risk:'DATA ONLY',...live,symbol,company:live.company||symbol,sector:live.sector||'Unclassified'});}return {...market,stocks:merged};}
function loadPrivateStored(){try{const raw=localStorage.getItem(LOCAL_KEY);return raw?JSON.parse(raw):null;}catch{return null;}}
function applyPrivateSnapshot(base,stored){if(!stored?.snapshot)return base;const snap=stored.snapshot;const out=clone(base);const by=new Map((out.stocks||[]).map(s=>[String(s.symbol||'').toUpperCase(),s]));for(const incoming of (Array.isArray(snap.stocks)?snap.stocks:[])){const symbol=String(incoming.symbol||'').trim().toUpperCase();if(!symbol)continue;const prior=by.get(symbol)||{symbol};by.set(symbol,{...prior,...incoming,symbol,state:incoming.state||'UNSCORED',risk:incoming.risk||'PRIVATE DATA'});}out.stocks=[...by.values()];out.market={...(out.market||{}),...(snap.market||{})};out.meta={...(out.meta||{}),privateLocalSnapshot:true,stockDataFresh:Array.isArray(snap.stocks)&&snap.stocks.length>0,indexDataFresh:!!snap.market,dataProvider:'Private browser snapshot',dataset:`Private browser snapshot — ${stored.name||'local file'}`,lastSuccessfulRefresh:snap.meta?.asOf||snap.meta?.lastSuccessfulRefresh||stored.importedAt};privateMeta={name:stored.name||'local file',importedAt:stored.importedAt,asOf:snap.meta?.asOf||snap.meta?.lastSuccessfulRefresh||'—'};return out;}
function csvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);return rows;}
const nk=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const num=v=>{if(v==null)return null;const x=Number(String(v).replace(/[%,$\s]/g,'').replace(/,/g,''));return Number.isFinite(x)?x:null;};
function pickIndex(headers,aliases){for(const a of aliases){const i=headers.indexOf(a);if(i>=0)return i;}return -1;}
function parseCsvSnapshot(text,fileName){const rows=csvRows(text);if(!rows.length)throw new Error('CSV is empty');let hi=-1,headers=[];for(let i=0;i<Math.min(rows.length,15);i++){const h=rows[i].map(nk);if(h.some(x=>['symbol','scrip','ticker','security','code'].includes(x))){hi=i;headers=h;break;}}if(hi<0)throw new Error('Could not find a SYMBOL/SCRIP/TICKER column in CSV');const si=pickIndex(headers,['symbol','scrip','ticker','security','code']);const ci=pickIndex(headers,['company','companyname','name']);const sec=pickIndex(headers,['sector','sectorname']);const pi=pickIndex(headers,['price','close','closingprice','current','last','rate']);const ch=pickIndex(headers,['changepercent','percentchange','pctchange','change']);const vi=pickIndex(headers,['volume','vol','shares','turnover']);const pei=pickIndex(headers,['pe','peratio','ttmpe']);const avi=pickIndex(headers,['avgvol','30dvolumeavg','30dayvolumeavg']);const stocks=[];for(const r of rows.slice(hi+1)){const symbol=String(r[si]||'').trim().toUpperCase();if(!symbol)continue;const s={symbol};if(ci>=0&&r[ci])s.company=r[ci];if(sec>=0&&r[sec])s.sector=r[sec];const p=pi>=0?num(r[pi]):null;if(p!=null)s.price=p;const c=ch>=0?num(r[ch]):null;if(c!=null)s.change=c;const v=vi>=0?num(r[vi]):null;if(v!=null)s.volume=v;const pe=pei>=0?num(r[pei]):null;if(pe!=null)s.pe=pe;const av=avi>=0?num(r[avi]):null;if(av!=null)s.avgVol=av;stocks.push(s);}if(!stocks.length)throw new Error('CSV contained no valid stock rows');return {meta:{asOf:new Date().toISOString(),source:`Private import: ${fileName}`},stocks};}
function parseSnapshotFile(name,text){if(name.toLowerCase().endsWith('.csv'))return parseCsvSnapshot(text,name);const obj=JSON.parse(text);if(Array.isArray(obj))return {meta:{asOf:new Date().toISOString(),source:`Private import: ${name}`},stocks:obj};if(!obj||typeof obj!=='object')throw new Error('JSON snapshot must be an object or array');return obj;}
async function load({manual=false}={}){const b=$('refresh');b.disabled=true;b.textContent=manual?'Reloading…':'Loading…';$('dataset').textContent='Loading PSX reference universe…';try{const ts=Date.now();const [mr,ur]=await Promise.all([fetch(`data/market.json?ts=${ts}`,{cache:'no-store'}),fetch(`data/universe.json?ts=${ts}`,{cache:'no-store'})]);if(!mr.ok)throw new Error(`Market dataset request failed (${mr.status})`);if(!ur.ok)throw new Error(`Universe dataset request failed (${ur.status})`);let market=sanitizePublicMarket(await mr.json());const universe=await ur.json();universeMeta=universe.meta||{};privateMeta=null;market=applyPrivateSnapshot(market,loadPrivateStored());db=mergeUniverse(universe,market);hydrate();render();const checked=new Date().toLocaleTimeString();$('dataset').textContent=db.meta.privateLocalSnapshot?`${db.meta.dataset} · private/local only · checked ${checked}`:`Public market snapshot is stale — load a private snapshot before market analysis · checked ${checked}`;}catch(err){console.error(err);$('dataset').textContent=`Refresh failed: ${err.message}`;}finally{b.disabled=false;b.textContent='Reload Data';}}
function hydrate(){const m=db.market||{};$('cards').innerHTML=[['KSE-100',m.kse100,m.kse100Change],['All Share',m.allShare,m.allShareChange],['OGTI',m.ogti,m.ogtiChange],['Universe',db.stocks.length,null]].map(x=>`<div class=card><small>${x[0]}</small><div class=value>${f(x[1])}</div>${x[2]!=null?`<div class=${x[2]>=0?'pos':'neg'}>${pct(x[2])}</div>`:''}</div>`).join('');$('sector').innerHTML='<option value="">All sectors</option>'+[...new Set(db.stocks.map(s=>s.sector||'Unclassified'))].sort().map(x=>`<option>${x}</option>`).join('');$('state').innerHTML='<option value="">All states</option>'+[...new Set(db.stocks.map(s=>s.state||'UNSCORED'))].sort().map(x=>`<option>${x}</option>`).join('');const universeStatus=universeMeta.complete===true?'Complete':'Incomplete';const mode=db.meta.privateLocalSnapshot?'Private browser snapshot':'Public demo only (stale)';$('statusgrid').innerHTML=`<p>Data mode: <b>${mode}</b></p><p>Universe size: <b>${db.stocks.length}</b></p><p>Universe source: <b>${universeMeta.source||'Reference master'}</b></p><p>Universe as of: <b>${universeMeta.asOf||'—'}</b></p><p>Universe status: <b>${universeStatus}</b></p><p>Market source: <b>${db.meta.dataProvider||'Public demo snapshot'}</b></p><p>Market as of: <b>${db.meta.lastSuccessfulRefresh||'—'}</b></p><p>Private file: <b>${privateMeta?.name||'—'}</b></p><p>Private imported: <b>${privateMeta?.importedAt||'—'}</b></p><p>Historical range: <b>${db.meta.historicalRangeStatus||'Verified values where available'}</b></p>`;$('clearLocal').classList.toggle('hidden',!db.meta.privateLocalSnapshot);}
function rows(){const q=$('q').value.toLowerCase(),sec=$('sector').value,pr=$('price').value,st=$('state').value;return db.stocks.filter(s=>{const price=s.price;return(!q||((s.symbol||'')+' '+(s.company||'')).toLowerCase().includes(q))&&(!sec||(s.sector||'Unclassified')===sec)&&(!st||(s.state||'UNSCORED')===st)&&(!$('pe').checked||(s.pe!=null&&s.pe<=10))&&(!pr||(price!=null&&((pr==='50'&&price<=50)||(pr==='10'&&price<10)||(pr==='100+'&&price>100))));}).sort((a,b)=>(b.tactical??0)-(a.tactical??0)||String(a.symbol).localeCompare(String(b.symbol)));}
function render(){const r=rows();$('count').textContent=`${r.length} of ${db.stocks.length} shares shown`;document.querySelector('tbody').innerHTML=r.map(s=>`<tr><td><b>${s.symbol}</b></td><td>${s.company||'—'}</td><td>${s.sector||'Unclassified'}</td><td>${f(s.price)}</td><td class=${s.change==null?'':s.change>=0?'pos':'neg'}>${pct(s.change)}</td><td title="${s.historicalSource||'Historical value not yet verified'}">${f(histLow(s))}</td><td title="${s.historicalSource||'Historical value not yet verified'}">${f(histHigh(s))}</td><td>${histPos(s)==null?'—':f(histPos(s))+'%'}</td><td>${f(s.pe)}</td><td>${f(s.avgVol)}</td><td>${score(s.tactical)}</td><td>${score(s.medium)}</td><td>${score(s.long)}</td><td>${score(s.entryQuality)}</td><td>${s.confidence==null?'—':f(s.confidence)+'%'}</td><td><span class=pill>${s.state||'UNSCORED'}</span></td><td><span class=pill>${s.risk||'DATA ONLY'}</span></td></tr>`).join('');const sm=db.stocks.filter(s=>s.price!=null&&s.price<=50).sort((a,b)=>(b.tactical??0)-(a.tactical??0));$('smallgrid').innerHTML=sm.map((s,i)=>`<div><small>#${i+1} · ${s.sector||'Unclassified'}</small><h3>${s.symbol} · Rs ${f(s.price)}</h3><p class=${s.change==null?'':s.change>=0?'pos':'neg'}>${pct(s.change)}</p><p>Lifetime range <b>${f(histLow(s))} – ${f(histHigh(s))}</b></p><p>Tactical <b>${score(s.tactical)}</b> · Entry Q <b>${score(s.entryQuality)}</b></p><span class=pill>${s.state||'UNSCORED'}</span></div>`).join('');}
$('loadLocal').addEventListener('click',()=>$('localFile').click());
$('localFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();const snapshot=parseSnapshotFile(file.name,text);const stored={name:file.name,importedAt:new Date().toISOString(),snapshot};localStorage.setItem(LOCAL_KEY,JSON.stringify(stored));await load({manual:true});}catch(err){alert(`Could not load snapshot: ${err.message}`);}finally{e.target.value='';}});
$('clearLocal').addEventListener('click',async()=>{localStorage.removeItem(LOCAL_KEY);await load({manual:true});});
['q','sector','price','state','pe'].forEach(id=>$(id).addEventListener(id==='q'?'input':'change',render));
$('refresh').addEventListener('click',()=>load({manual:true}));
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(b.dataset.view).classList.remove('hidden');}));
load();
